# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpv_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fads',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
